name: Deploy
on: deployment
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Start deployment
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ github.token }}
          state: "in_progress"
          deployment_id: ${{ github.event.deployment.id }}
      - name: Deployment context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo $GITHUB_CONTEXT
      - name: Mark deployment as success
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ github.token }}
          state: "success"
          deployment_id: ${{ github.event.deployment.id }}
      - name: Mark deployment as failure
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: ${{ github.token }}
          state: "failure"
          deployment_id: ${{ github.event.deployment.id }}
